package co.za.access.Profiler.profile.model;

public enum CareerCategory {
    HEALTHCARE,
    ENGINEERING_AND_TECHNOLOGY,
    BUSINESS_AND_FINANCE,
    EDUCATION_AND_TRAINING,
    ARTS_DESIGN_AND_MEDIA,
    LAW_AND_PUBLIC_POLICY,
    SCIENCE_AND_RESEARCH,
    SKILLED_TRADES_AND_TECHNICAL_SERVICES,
    INFORMATION_TECHNOLOGY,
    HOSPITALITY_AND_TOURISM,
    SOCIAL_SERVICES,
    SALES_AND_MARKETING,
    AGRICULTURE_AND_NATURAL_RESOURCES,
    TRANSPORTATION_AND_LOGISTICS,
    GOVERNMENT_AND_PUBLIC_ADMINISTRATION
}

